version: "3"

networks:
  default:
    external:
      name: devocmysqlnet

services:
  redis:
    build:
      context: ./redis
    command: ["redis-server", "--tls-port", "6379", "--port", "0", "--tls-cert-file", "/tls/redis.crt", "--tls-key-file", "/tls/redis.key", "--tls-ca-cert-file", "/tls/ca.crt", "--tls-auth-clients", "no"]
    container_name: ${REDIS_NAME}
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
